
package Vistas;

import Clases.*;
import Controladores.*;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

public class Vista extends javax.swing.JFrame {
    ControladorClientes controladorClientes;
    ControladorPlanes controladorPlanes;
    ControladorMascotas controladorMascotas;
    ControladorPagos controladorPagos;

    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
        this.controladorClientes = new ControladorClientes();
        this.controladorPlanes = new ControladorPlanes();      
        this.controladorMascotas = new ControladorMascotas();
        this.controladorPagos = new ControladorPagos();
        setComboBoxPlanes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdentificacionCliente = new javax.swing.JTextField();
        txtNombresCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        btnCrearCliente = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnVerMascotas = new javax.swing.JButton();
        btnLimpiarClientes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoMascota = new javax.swing.JTextField();
        txtNombreMascota = new javax.swing.JTextField();
        txtEdadMascota = new javax.swing.JTextField();
        txtPesoMascota = new javax.swing.JTextField();
        comboEspecie = new javax.swing.JComboBox<>();
        btnCrearMascota = new javax.swing.JButton();
        btnConsultarMascota = new javax.swing.JButton();
        btnEditarMascota = new javax.swing.JButton();
        btnEliminarMascota = new javax.swing.JButton();
        txtIdDueno = new javax.swing.JTextField();
        btnLimpiarMascotas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDescripcionPlan = new javax.swing.JTextField();
        txtPrecioPlan = new javax.swing.JTextField();
        btnCrearPlan = new javax.swing.JButton();
        btnConsultarPlan = new javax.swing.JButton();
        btnEditarPlan = new javax.swing.JButton();
        btnEliminarPlan = new javax.swing.JButton();
        comboNombrePlan = new javax.swing.JComboBox<>();
        btnLimpiarPlanes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIdPago = new javax.swing.JTextField();
        txtMontoPago = new javax.swing.JTextField();
        txtCuotasPago = new javax.swing.JTextField();
        txtFechaPago = new javax.swing.JTextField();
        txtIdMascota = new javax.swing.JTextField();
        btnRegistrarPago = new javax.swing.JButton();
        btnConsultarPago = new javax.swing.JButton();
        btnEditarPago = new javax.swing.JButton();
        btnEliminarPago = new javax.swing.JButton();
        btnLimpiarPagos = new javax.swing.JButton();
        cmbPlanPagos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Identificación");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Dirección");

        jLabel6.setText("Teléfono");

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnVerMascotas.setText("Ver mascotas");
        btnVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMascotasActionPerformed(evt);
            }
        });

        btnLimpiarClientes.setText("Limpiar campos");
        btnLimpiarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdentificacionCliente)
                    .addComponent(txtNombresCliente)
                    .addComponent(txtApellidosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionCliente)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnVerMascotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarClientes)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtNombresCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMascotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCliente)
                    .addComponent(btnConsultarCliente)
                    .addComponent(btnEditarCliente)
                    .addComponent(btnEliminarCliente)
                    .addComponent(btnLimpiarClientes))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jLabel7.setText("Código");

        jLabel8.setText("Nombre");

        jLabel9.setText("Edad");

        jLabel10.setText("Peso");

        jLabel11.setText("Especie");

        jLabel12.setText("DNI Cliente");

        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canino", "Felino" }));
        comboEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecieActionPerformed(evt);
            }
        });

        btnCrearMascota.setText("Crear");
        btnCrearMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMascotaActionPerformed(evt);
            }
        });

        btnConsultarMascota.setText("Consultar");
        btnConsultarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMascotaActionPerformed(evt);
            }
        });

        btnEditarMascota.setText("Editar");
        btnEditarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMascotaActionPerformed(evt);
            }
        });

        btnEliminarMascota.setText("Eliminar");
        btnEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMascotaActionPerformed(evt);
            }
        });

        btnLimpiarMascotas.setText("Limpiar Campos");
        btnLimpiarMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMascotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreMascota)
                            .addComponent(txtEdadMascota)
                            .addComponent(txtPesoMascota))))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarMascotas)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEdadMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPesoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMascota)
                    .addComponent(btnConsultarMascota)
                    .addComponent(btnEditarMascota)
                    .addComponent(btnEliminarMascota)
                    .addComponent(btnLimpiarMascotas))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mascotas", jPanel4);

        jLabel15.setText("Nombre");

        jLabel16.setText("Descripción");

        jLabel17.setText("Precio");

        txtPrecioPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioPlanActionPerformed(evt);
            }
        });

        btnCrearPlan.setText("Crear");
        btnCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlanActionPerformed(evt);
            }
        });

        btnConsultarPlan.setText("Consultar");
        btnConsultarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPlanActionPerformed(evt);
            }
        });

        btnEditarPlan.setText("Editar");
        btnEditarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlanActionPerformed(evt);
            }
        });

        btnEliminarPlan.setText("Eliminar");
        btnEliminarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlanActionPerformed(evt);
            }
        });

        comboNombrePlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienestar", "Élite", "Diamante" }));

        btnLimpiarPlanes.setText("Limpiar Campos");
        btnLimpiarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPlanesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboNombrePlan, 0, 178, Short.MAX_VALUE)
                                .addGap(332, 332, 332))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnCrearPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarPlanes)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDescripcionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPrecioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPlan)
                    .addComponent(btnConsultarPlan)
                    .addComponent(btnEditarPlan)
                    .addComponent(btnEliminarPlan)
                    .addComponent(btnLimpiarPlanes))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planes", jPanel2);

        jLabel13.setText("Nro. Pago");

        jLabel14.setText("Monto");

        jLabel18.setText("Cuotas");

        jLabel19.setText("Fecha");

        jLabel20.setText("idMascota");

        jLabel21.setText("Plan");

        btnRegistrarPago.setText("Registrar");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        btnConsultarPago.setText("Consultar pago");
        btnConsultarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPagoActionPerformed(evt);
            }
        });

        btnEditarPago.setText("Guardar cambios");
        btnEditarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPagoActionPerformed(evt);
            }
        });

        btnEliminarPago.setText("Eliminar registro");
        btnEliminarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPagoActionPerformed(evt);
            }
        });

        btnLimpiarPagos.setText("Limpiar campos");
        btnLimpiarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnRegistrarPago)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarPago)
                .addGap(18, 18, 18)
                .addComponent(btnEditarPago)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPago)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(txtMontoPago)
                            .addComponent(txtCuotasPago))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPlanPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFechaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtIdMascota, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnLimpiarPagos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20)
                    .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(txtCuotasPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPlanPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPago)
                    .addComponent(btnConsultarPago)
                    .addComponent(btnEditarPago)
                    .addComponent(btnEliminarPago))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarPagos)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", jPanel5);

        jLabel1.setText("Veterinaria 2.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMascotaActionPerformed
        try{
            Integer.parseInt(txtCodigoMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un número");
        }
        int codigo = Integer.parseInt(txtCodigoMascota.getText());
        this.controladorMascotas.eliminarMascota(codigo);
        JOptionPane.showMessageDialog(this, "Los datos de la mascota han sido eliminados");
        this.borrarCamposMascota();
        
    }//GEN-LAST:event_btnEliminarMascotaActionPerformed

    private void btnEditarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMascotaActionPerformed
        String nombre = txtNombreMascota.getText();

        try{
            Integer.parseInt(txtEdadMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La edad debe ser un número");
        }
        int edad = Integer.parseInt(txtEdadMascota.getText());

        try{
            Float.parseFloat(txtPesoMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El peso debe ser un número");

        }
        float peso = Float.parseFloat(txtPesoMascota.getText());

        String dueno = txtIdDueno.getText();
        
        String especie = comboEspecie.getSelectedItem().toString();
        if(nombre.equals("")||dueno.equals("")){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
        }else{
            try{
                clsCliente c =this.controladorClientes.getCliente(dueno);
                clsMascota m = new clsMascota(nombre,edad,peso,especie,c);
                this.controladorMascotas.setMascota(m);
                JOptionPane.showMessageDialog(this, "Los datos de la mascota de "+c.getApellidosCliente()+", "+c.getNombresCliente()+" han sido actualizados.");
                this.borrarCamposMascota();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "No se encontró el DNI del cliente en el sistema. Revise que el DNI sea correcto");
            }
        }
        
        
    }//GEN-LAST:event_btnEditarMascotaActionPerformed

    private void btnConsultarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMascotaActionPerformed
        
        try{
            Integer.parseInt(txtCodigoMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un número");
        }
        int codigo = Integer.parseInt(txtCodigoMascota.getText());
        try{
            clsMascota m=controladorMascotas.getMascota(codigo);
            txtNombreMascota.setText(m.getNombreMascota());
            txtEdadMascota.setText(m.getEdadMascota()+"");
            txtPesoMascota.setText(m.getPesoMascota()+"");
            txtIdDueno.setText(m.getDuenoMascota().getDocumentoCliente());
            comboEspecie.setSelectedItem(m.getEspecieMascota());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se encontró una mascota asociada a ese código");
            this.borrarCamposMascota();
        }


    }//GEN-LAST:event_btnConsultarMascotaActionPerformed

    private void btnCrearMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMascotaActionPerformed

        String nombre = txtNombreMascota.getText();

        try{
            Integer.parseInt(txtEdadMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La edad debe ser un número");
        }
        int edad = Integer.parseInt(txtEdadMascota.getText());

        try{
            Float.parseFloat(txtPesoMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El peso debe ser un número");

        }
        float peso = Float.parseFloat(txtPesoMascota.getText());

        String dueno = txtIdDueno.getText();
        
        String especie = comboEspecie.getSelectedItem().toString();
        if(nombre.equals("")||dueno.equals("")){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
        }else{
            try{
                clsCliente c =this.controladorClientes.getCliente(dueno);
                clsMascota m = new clsMascota(nombre,edad,peso,especie,c);
                this.controladorMascotas.agregarMascota(m);
                JOptionPane.showMessageDialog(this, "La mascota ha sido agregada y asociada al cliente: "+c.getApellidosCliente()+", "+c.getNombresCliente());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "No se encontró el DNI del cliente en el sistema. Revise que el DNI sea correcto");
            }

        }

    }//GEN-LAST:event_btnCrearMascotaActionPerformed

    private void comboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspecieActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        String documento = txtIdentificacionCliente.getText();
        
        this.controladorClientes.eliminarCliente(documento);
        this.borrarCamposCliente();
        JOptionPane.showMessageDialog(this, "La información del cliente ha sido eliminada");
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        String documento = txtIdentificacionCliente.getText();
        String nombres = txtNombresCliente.getText();
        String apellidos = txtApellidosCliente.getText();
        String direccion = txtDireccionCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        try{
            if(documento.equals("")||nombres.equals("")||apellidos.equals("")||direccion.equals("")||telefono.equals("")){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
            }else{
                clsCliente cliente = new clsCliente(documento,nombres,apellidos,direccion,telefono);
                JOptionPane.showMessageDialog(this, "El cliente ha sido actualizado");
                this.controladorClientes.setCliente(cliente);
                this.borrarCamposCliente();
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El precio debe ser un número");
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        String documento = txtIdentificacionCliente.getText();
        try{
            clsCliente cliente = this.controladorClientes.getCliente(documento);
            txtNombresCliente.setText(cliente.getNombresCliente());
            txtApellidosCliente.setText(cliente.getApellidosCliente());
            txtDireccionCliente.setText(cliente.getDireccionCliente());
            txtTelefonoCliente.setText(cliente.getTelefonoCliente());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El cliente no se encuentra en el sistema");
            this.borrarCamposCliente();
        }

    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        String documento = txtIdentificacionCliente.getText();
        String nombres = txtNombresCliente.getText();
        String apellidos = txtApellidosCliente.getText();
        String direccion = txtDireccionCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        if(documento.equals("")||nombres.equals("")||apellidos.equals("")||direccion.equals("")||telefono.equals("")){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
        }else{
            clsCliente c = new clsCliente(documento, nombres, apellidos, direccion, telefono);
            JOptionPane.showMessageDialog(this, "El cliente ha sido creado");
            this.borrarCamposCliente();
            controladorClientes.agregarCliente(c);
        }
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void txtPrecioPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioPlanActionPerformed

    private void btnCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlanActionPerformed

        String nombre = comboNombrePlan.getSelectedItem().toString();
        String descripcion = txtDescripcionPlan.getText();
        try{
            float precio= Float.parseFloat(txtPrecioPlan.getText());
            if(descripcion.equals("")){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
            }else{
                clsPlan plan = new clsPlan(nombre,descripcion,precio);
                JOptionPane.showMessageDialog(this, "El plan ha sido creado");
                this.controladorPlanes.agregarPlan(plan);
                this.borrarCamposPlan();
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El precio debe ser un número");
        }

    }//GEN-LAST:event_btnCrearPlanActionPerformed

    private void btnConsultarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPlanActionPerformed
        String nombre = comboNombrePlan.getSelectedItem().toString();
        try{
            clsPlan plan = this.controladorPlanes.getPlan(nombre);
            txtDescripcionPlan.setText(plan.getDescripcionPlan());
            txtPrecioPlan.setText(plan.getPrecioPlan()+"");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El plan no se encuentra en el sistema");
            this.borrarCamposPlan();
        }
    }//GEN-LAST:event_btnConsultarPlanActionPerformed
    
    private void btnEditarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlanActionPerformed
        String nombre = comboNombrePlan.getSelectedItem().toString();
        String descripcion = txtDescripcionPlan.getText();
        try{
            float precio= Float.parseFloat(txtPrecioPlan.getText());
            if(descripcion.equals("")){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar");
            }else{
                clsPlan plan = new clsPlan(nombre,descripcion,precio);
                JOptionPane.showMessageDialog(this, "El plan ha sido actualizado");
                this.controladorPlanes.setPlan(plan);
                this.borrarCamposPlan();
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El precio debe ser un número");
        }
        
    }//GEN-LAST:event_btnEditarPlanActionPerformed

    private void btnEliminarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlanActionPerformed
        String nombre = comboNombrePlan.getSelectedItem().toString();
        this.controladorPlanes.eliminarPlan(nombre);
        this.borrarCamposPlan();
        JOptionPane.showMessageDialog(this, "La información del plan ha sido eliminada");
    }//GEN-LAST:event_btnEliminarPlanActionPerformed

    private void btnVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMascotasActionPerformed
        String documento = txtIdentificacionCliente.getText();
        String listado = "";
        for(Object mascota: controladorMascotas.getMascotasCliente(documento)){
            listado = listado + mascota + "\n";
        };
        JOptionPane.showMessageDialog(this, listado);
    }//GEN-LAST:event_btnVerMascotasActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        try{
            Float.parseFloat(txtMontoPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El monto debe ser un número");
        }
        float montoPago = Float.parseFloat(txtMontoPago.getText());
        
        try{
            Integer.parseInt(txtCuotasPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuotas igual o mayor a 1 ");
        }
        int cuotasPago = Integer.parseInt(txtCuotasPago.getText());
        
        String fechaPago=txtFechaPago.getText();        
        try{
            Integer.parseInt(txtIdMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El código debe ser un número");
        }
        int idMascota = Integer.parseInt(txtIdMascota.getText());
                
        String nombrePlan = cmbPlanPagos.getSelectedItem().toString();
        clsMascota mascotaPago = this.controladorMascotas.getMascota(idMascota);
        String msg1 = "";
        if(mascotaPago==null){
            msg1 = "No se encontró una mascota con ese código. ";
        }
        clsPlan planPago = this.controladorPlanes.getPlan(nombrePlan);
        try{
            clsPago pago = new clsPago(montoPago,cuotasPago,fechaPago,mascotaPago,planPago);
            JOptionPane.showMessageDialog(this, "Se registro el pago exitosamente y fue asociado a la mascota "+idMascota);
            this.controladorPagos.agregarPago(pago);
            this.borrarCamposPago();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No fue posible registrar el pago. "+msg1);
        }
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void btnConsultarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPagoActionPerformed
        int idPago = Integer.parseInt(txtIdPago.getText());
        try{
            clsPago pago = this.controladorPagos.getPago(idPago);            
            txtMontoPago.setText(pago.getMonto()+"");
            txtCuotasPago.setText(pago.getCuotas()+"");
            txtFechaPago.setText(pago.getFecha());
            txtIdMascota.setText(pago.getMascotaPago().getCodigoMascota()+"");
            cmbPlanPagos.setSelectedItem(pago.getPlanPago().getNombrePlan());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El plan no se encuentra en el sistema");
            this.borrarCamposPago();
        }
    }//GEN-LAST:event_btnConsultarPagoActionPerformed

    private void btnEditarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPagoActionPerformed
        try{
            Integer.parseInt(txtIdPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un número");
        }
        int idPago = Integer.parseInt(txtIdPago.getText()); 
        try{
            Float.parseFloat(txtMontoPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El monto debe ser un número");
        }
        float montoPago = Float.parseFloat(txtMontoPago.getText());
        try{
            Integer.parseInt(txtCuotasPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuotas igual o mayor a 1 ");
        }
        int cuotasPago = Integer.parseInt(txtCuotasPago.getText());
        String fechaPago=txtFechaPago.getText();
        
        try{
            Integer.parseInt(txtIdMascota.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El código debe ser un número");
        }
        int idMascota = Integer.parseInt(txtIdMascota.getText());
                
        String nombrePlan = cmbPlanPagos.getSelectedItem().toString();
        clsMascota mascotaPago = this.controladorMascotas.getMascota(idMascota);
        String msg1 = "";
        if(mascotaPago==null){
            msg1 = "No se encontró una mascota con ese código. ";
        }
        clsPlan planPago = this.controladorPlanes.getPlan(nombrePlan);
        try{
            clsPago pago = new clsPago(idPago,montoPago,cuotasPago,fechaPago,mascotaPago,planPago);
            this.controladorPagos.setPago(pago);            
            JOptionPane.showMessageDialog(this, "Se modificaron los datos del pago asociado a la mascota:  "+idMascota);
            this.borrarCamposPago();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No fue posible registrar el pago. "+msg1);
        }
    }//GEN-LAST:event_btnEditarPagoActionPerformed

    private void btnEliminarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPagoActionPerformed
        try{
            Integer.parseInt(txtIdPago.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un número");
        }
        int idPago = Integer.parseInt(txtIdPago.getText()); 
        this.controladorPagos.eliminarPago(idPago);
        JOptionPane.showMessageDialog(this, "Los datos del pago fueron eliminados");
        this.borrarCamposPago();
        
    }//GEN-LAST:event_btnEliminarPagoActionPerformed

    private void btnLimpiarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarClientesActionPerformed
        borrarCamposCliente();
    }//GEN-LAST:event_btnLimpiarClientesActionPerformed

    private void btnLimpiarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMascotasActionPerformed
        borrarCamposMascota();
    }//GEN-LAST:event_btnLimpiarMascotasActionPerformed

    private void btnLimpiarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPlanesActionPerformed
        borrarCamposPlan();
    }//GEN-LAST:event_btnLimpiarPlanesActionPerformed

    private void btnLimpiarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPagosActionPerformed
        borrarCamposPago();
    }//GEN-LAST:event_btnLimpiarPagosActionPerformed

    private void borrarCamposPago(){
        txtIdPago.setText("");
        txtMontoPago.setText("");
        txtCuotasPago.setText("");
        txtFechaPago.setText("");
        txtIdMascota.setText("");        
    }
    
    private void borrarCamposCliente(){
        txtIdentificacionCliente.setText("");
        txtNombresCliente.setText("");
        txtApellidosCliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
    }
    private void borrarCamposPlan(){
        comboNombrePlan.setSelectedItem("Bienestar");
        txtDescripcionPlan.setText("");
        txtPrecioPlan.setText("");  
    }
    
    private void borrarCamposMascota(){
        txtCodigoMascota.setText("");
        txtNombreMascota.setText("");
        txtEdadMascota.setText("");
        txtPesoMascota.setText("");        
        comboEspecie.setSelectedItem("Canino");
        txtIdDueno.setText("");
    }
   
    private void setComboBoxPlanes(){
        for(clsPlan plan:controladorPlanes.getAllPlanes()){
            cmbPlanPagos.addItem(plan.getNombrePlan());
        }
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarMascota;
    private javax.swing.JButton btnConsultarPago;
    private javax.swing.JButton btnConsultarPlan;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearMascota;
    private javax.swing.JButton btnCrearPlan;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarMascota;
    private javax.swing.JButton btnEditarPago;
    private javax.swing.JButton btnEditarPlan;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarMascota;
    private javax.swing.JButton btnEliminarPago;
    private javax.swing.JButton btnEliminarPlan;
    private javax.swing.JButton btnLimpiarClientes;
    private javax.swing.JButton btnLimpiarMascotas;
    private javax.swing.JButton btnLimpiarPagos;
    private javax.swing.JButton btnLimpiarPlanes;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton btnVerMascotas;
    private javax.swing.JComboBox<String> cmbPlanPagos;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JComboBox<String> comboNombrePlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtCodigoMascota;
    private javax.swing.JTextField txtCuotasPago;
    private javax.swing.JTextField txtDescripcionPlan;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtEdadMascota;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtIdDueno;
    private javax.swing.JTextField txtIdMascota;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtIdentificacionCliente;
    private javax.swing.JTextField txtMontoPago;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtPesoMascota;
    private javax.swing.JTextField txtPrecioPlan;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

}
